// Home Base
export const homeBase = {
    "Hong Kong": {
        "country": "China",
        "iata": "HKG",
        "icao": "VHHH",
        "city": "Hong Kong",
        "runway": "07",
        "allRunway": "07L/25R, 07C/25C, 07R/25L",
    },
};

// Dictionary list of destinations
export const destinations = {
    "Narita": {
        "country": "Japan",
        "iata": "NRT",
        "icao": "RJAA",
        "city": "Tokyo",
        "runway": "16",
        "allRunway": "16L/34R, 16R/34L",
    },
    "Osaka": {
        "country": "Japan",
        "iata": "KIX",
        "icao": "RJBB",
        "city": "Osaka",
        "runway": "06",
        "allRunway": "06L/24R, 06R/24L",
    },
    "Nagoya": {
        "country": "Japan",
        "iata": "NGO",
        "icao": "RJGG",
        "city": "Nagoya",
        "runway": "18",
        "allRunway": "18/36",
    },
    "Fukuoka": {
        "country": "Japan",
        "iata": "FUK",
        "icao": "RJFF",
        "city": "Fukuoka",
        "runway": "16",
        "allRunway": "16/34",
    },
    "Haneda": {
        "country": "Japan",
        "iata": "HND",
        "icao": "RJTT",
        "city": "Tokyo",
        "runway": "16",
        "allRunway": "16L/34R, 16R/34L, 05/23",
    },
    "Kagoshima": {
        "country": "Japan",
        "iata": "KOJ",
        "icao": "RJFK",
        "city": "Kagoshima",
        "runway": "34",
        "allRunway": "16/34",
    },
    "Sapporo": {
        "country": "Japan",
        "iata": "CTS",
        "icao": "RJCC",
        "city": "Sapporo",
        "runway": "19",
        "allRunway": "01L/19R, 01R/19L",
    },
    "Naha": {
        "country": "Japan",
        "iata": "OKA",
        "icao": "ROAH",
        "city": "Okinawa",
        "runway": "18",
        "allRunway": "18/36",
    },
    "Kumamoto": {
        "country": "Japan",
        "iata": "KMJ",
        "icao": "RJFT",
        "city": "Kumamoto",
        "runway": "07",
        "allRunway": "07/25",
    },
    "Hakodate": {
        "country": "Japan",
        "iata": "HKD",
        "icao": "RJCH",
        "city": "Hakodate",
        "runway": "12",
        "allRunway": "12/30",
    },
    "Yonago": {
        "country": "Japan",
        "iata": "YGJ",
        "icao": "RJOH",
        "city": "Yonago",
        "runway": "07",
        "allRunway": "07/25",
    },
    "Sendai": {
        "country": "Japan",
        "iata": "SDJ",
        "icao": "RJSS",
        "city": "Sendai",
        "runway": "09",
        "allRunway": "09/27",
    },
    "Miyazaki": {
        "country": "Japan",
        "iata": "KMI",
        "icao": "RJFM",
        "city": "Miyazaki",
        "runway": "09",
        "allRunway": "09/27",
    },
    "Nagasaki": {
        "country": "Japan",
        "iata": "NGS",
        "icao": "RJFU",
        "city": "Nagasaki",
        "runway": "14",
        "allRunway": "14/32",
    },
    "Okayama": {
        "country": "Japan",
        "iata": "OKJ",
        "icao": "RJOB",
        "city": "Okayama",
        "runway": "07",
        "allRunway": "07/25",
    },
    "Miho": {
        "country": "Japan",
        "iata": "YGJ",
        "icao": "RJOH",
        "city": "Miho",
        "runway": "07",
        "allRunway": "07/25",
    },
    "Taipei": {
        "country": "Taiwan",
        "iata": "TPE",
        "icao": "RCTP",
        "city": "Taipei",
        "runway": "05",
        "allRunway": "05L/23R, 05R/23L",
    },
    "Taichung": {
        "country": "Taiwan",
        "iata": "RMQ",
        "icao": "RCMQ",
        "city": "Taichung",
        "runway": "18",
        "allRunway": "18/36",
    },
    "Kaohsiung": {
        "country": "Taiwan",
        "iata": "KHH",
        "icao": "RCKH",
        "city": "Kaohsiung",
        "runway": "09",
        "allRunway": "09/27",
    },
    "Bangkok": {
        "country": "Thailand",
        "iata": "BKK",
        "icao": "VTBS",
        "city": "Bangkok",
        "runway": "19",
        "allRunway": "01L/19R, 01R/19L",
    },
    "Bangkok Don Mueang": {
        "country": "Thailand",
        "iata": "DMK",
        "icao": "VTBD",
        "city": "Bangkok",
        "runway": "21",
        "allRunway": "03L/21R, 03R/21L",
    },
    "Chiang Mai": {
        "country": "Thailand",
        "iata": "CNX",
        "icao": "VTCC",
        "city": "Chiang Mai",
        "runway": "18",
        "allRunway": "18/36",
    },
    "Koh Samui": {
        "country": "Thailand",
        "iata": "USM",
        "icao": "VTSM",
        "city": "Koh Samui",
        "runway": "17",
        "allRunway": "17/35",
    },
    "Phuket": {
        "country": "Thailand",
        "iata": "HKT",
        "icao": "VTSP",
        "city": "Phuket",
        "runway": "09",
        "allRunway": "09/27",
    },
    "Krabi": {
        "country": "Thailand",
        "iata": "KBV",
        "icao": "VTSG",
        "city": "Krabi",
        "runway": "14",
        "allRunway": "14/32",
    },
    "Luang Prabang": {
        "country": "Laos",
        "iata": "LPQ",
        "icao": "VLLB",
        "city": "Luang Prabang",
        "runway": "23",
        "allRunway": "05/23",
    },
    "Vientiane": {
        "country": "Laos",
        "iata": "VTE",
        "icao": "VLVT",
        "city": "Vientiane",
        "runway": "13",
        "allRunway": "13/31",
    },
    "Bali": {
        "country": "Indonesia",
        "iata": "DPS",
        "icao": "WADD",
        "city": "Bali",
        "runway": "09",
        "allRunway": "09/27",
    },
    "Bandung": {
        "country": "Indonesia",
        "iata": "BDO",
        "icao": "WICC",
        "city": "Bandung",
        "runway": "11",
        "allRunway": "11/29",
    },
    "Jakarta": {
        "country": "Indonesia",
        "iata": "CGK",
        "icao": "WIII",
        "city": "Jakarta",
        "runway": "07",
        "allRunway": "07L/25R, 07R/25L",
    },
    "Surabaya": {
        "country": "Indonesia",
        "iata": "SUB",
        "icao": "WARR",
        "city": "Surabaya",
        "runway": "10",
        "allRunway": "10/28",
    },
    "Da Nang": {
        "country": "Vietnam",
        "iata": "DAD",
        "icao": "VVDN",
        "city": "Da Nang",
        "runway": "17",
        "allRunway": "17L/35R, 17R/35L",
    },
    "Hanoi": {
        "country": "Vietnam",
        "iata": "HAN",
        "icao": "VVNB",
        "city": "Hanoi",
        "runway": "11",
        "allRunway": "11L/29R, 11R/29L",
    },
    "Ho Chi Minh": {
        "country": "Vietnam",
        "iata": "SGN",
        "icao": "VVTS",
        "city": "Ho Chi Minh",
        "runway": "25",
        "allRunway": "07L/25R, 07R/25L",
    },
    "Singapore": {
        "country": "Singapore",
        "iata": "SIN",
        "icao": "WSSS",
        "city": "Singapore",
        "runway": "02",
        "allRunway": "02L/20R, 02C/20C, 02R/20L",
    },
    "Kuala Lumpur": {
        "country": "Malaysia",
        "iata": "KUL",
        "icao": "WMKK",
        "city": "Kuala Lumpur",
        "runway": "14",
        "allRunway": "14L/32R, 14R/32L",
    },
    "Penang": {
        "country": "Malaysia",
        "iata": "PEN",
        "icao": "WMKP",
        "city": "Penang",
        "runway": "04",
        "allRunway": "04/22",
    },
    "Langkawi": {
        "country": "Malaysia",
        "iata": "LGK",
        "icao": "WMKL",
        "city": "Langkawi",
        "runway": "03",
        "allRunway": "03/21",
    },
    "Beijing": {
        "country": "China",
        "iata": "PEK",
        "icao": "ZBAA",
        "city": "Beijing",
        "runway": "36",
        "allRunway": "18L/36R, 18R/36L",
    },
    "Beijing Daxing": {
        "country": "China",
        "iata": "PKX",
        "icao": "ZBAD",
        "city": "Beijing",
        "runway": "17",
        "allRunway": "17L/35R, 17R/35L",
    },
    "Shanghai": {
        "country": "China",
        "iata": "PVG",
        "icao": "ZSPD",
        "city": "Shanghai",
        "runway": "17",
        "allRunway": "17L/35R, 17R/35L",
    },
    "Shanghai Hongqiao": {
        "country": "China",
        "iata": "SHA",
        "icao": "ZSSS",
        "city": "Shanghai",
        "runway": "18",
        "allRunway": "18L/36R, 18R/36L",
    },
    "Chengdu": {
        "country": "China",
        "iata": "CTU",
        "icao": "ZUUU",
        "city": "Chengdu",
        "runway": "20",
        "allRunway": "02L/20R, 02R/20L",
    },
    "Chengdu Tianfu": {
        "country": "China",
        "iata": "TFU",
        "icao": "ZUAI",
        "city": "Chengdu",
        "runway": "20",
        "allRunway": "01L/19R, 01R/19L",
    },
    "Chongqing": {
        "country": "China",
        "iata": "CKG",
        "icao": "ZUCK",
        "city": "Chongqing",
        "runway": "02",
        "allRunway": "02L/20R, 02R/20L",
    },
    "Dalian": {
        "country": "China",
        "iata": "DLC",
        "icao": "ZYTL",
        "city": "Dalian",
        "runway": "10",
        "allRunway": "10/28",
    },
    "Guiyang": {
        "country": "China",
        "iata": "KWE",
        "icao": "ZUGY",
        "city": "Guiyang",
        "runway": "01",
        "allRunway": "01/19",
    },
    "Hangzhou": {
        "country": "China",
        "iata": "HGH",
        "icao": "ZSHC",
        "city": "Hangzhou",
        "runway": "06",
        "allRunway": "06/24",
    },
    "Harbin": {
        "country": "China",
        "iata": "HRB",
        "icao": "ZYHB",
        "city": "Harbin",
        "runway": "05",
        "allRunway": "05/23",
    },
    "Kunming": {
        "country": "China",
        "iata": "KMG",
        "icao": "ZPPP",
        "city": "Kunming",
        "runway": "21",
        "allRunway": "03/21",
    },
    "Nanjing": {
        "country": "China",
        "iata": "NKG",
        "icao": "ZSNJ",
        "city": "Nanjing",
        "runway": "07",
        "allRunway": "07/25",
    },
    "Sanya": {
        "country": "China",
        "iata": "SYX",
        "icao": "ZJSY",
        "city": "Sanya",
        "runway": "08",
        "allRunway": "08/26",
    },
    "Haikou": {
        "country": "China",
        "iata": "HAK",
        "icao": "ZJHK",
        "city": "Haikou",
        "runway": "09",
        "allRunway": "09/27",
    },
    "Nanchang": {
        "country": "China",
        "iata": "KHN",
        "icao": "ZSCN",
        "city": "Nanchang",
        "runway": "03",
        "allRunway": "03/21",
    },
    "Urumqi": {
        "country": "China",
        "iata": "URC",
        "icao": "ZWWW",
        "city": "Urumqi",
        "runway": "25",
        "allRunway": "07/25",
    },
    "Xian": {
        "country": "China",
        "iata": "XIY",
        "icao": "ZLXY",
        "city": "Xian",
        "runway": "05",
        "allRunway": "05L/23R, 05R/23L",
    },
    "Yinchuan": {
        "country": "China",
        "iata": "INC",
        "icao": "ZLIC",
        "city": "Yinchuan",
        "runway": "21",
        "allRunway": "03/21",
    },
    "Dunguang": {
        "country": "China",
        "iata": "DNH",
        "icao": "ZLDH",
        "city": "Dunguang",
        "runway": "25",
        "allRunway": "07/25",
    },
    "Gold Coast": {
        "country": "Australia",
        "iata": "OOL",
        "icao": "YBCG",
        "city": "Gold Coast",
        "runway": "14",
        "allRunway": "14/32",
    },
    "Brisbane": {
        "country": "Australia",
        "iata": "BNE",
        "icao": "YBBN",
        "city": "Brisbane",
        "runway": "01",
        "allRunway": "01L/19R, 01R/19L",
    },
    "Cairns": {
        "country": "Australia",
        "iata": "CNS",
        "icao": "YBCS",
        "city": "Cairns",
        "runway": "15",
        "allRunway": "15/33",
    },
    "Melbourne": {
        "country": "Australia",
        "iata": "MEL",
        "icao": "YMML",
        "city": "Melbourne",
        "runway": "16",
        "allRunway": "16/34",
    },
    "Perth": {
        "country": "Australia",
        "iata": "PER",
        "icao": "YPPH",
        "city": "Perth",
        "runway": "21",
        "allRunway": "03/21, 06/24",
    },
    "Sydney": {
        "country": "Australia",
        "iata": "SYD",
        "icao": "YSSY",
        "city": "Sydney",
        "runway": "16",
        "allRunway": "16L/34R, 16R/34L, 07/25"
    },
    "Male": {
        "country": "Maldives",
        "iata": "MLE",
        "icao": "VRMM",
        "city": "Male",
        "runway": "18",
        "allRunway": "18/36"
    },
    "Seoul": {
        "country": "South Korea",
        "iata": "ICN",
        "icao": "RKSI",
        "city": "Seoul",
        "runway": "33",
        "allRunway": "15L/33R, 15R/33L"
    },
    "Busan": {
        "country": "South Korea",
        "iata": "PUS",
        "icao": "RKPP",
        "city": "Busan",
        "runway": "36",
        "allRunway": "18/36"
    },
    "Jeju": {
        "country": "South Korea",
        "iata": "CJU",
        "icao": "RKPC",
        "city": "Jeju",
        "runway": "07",
        "allRunway": "07/25"
    },
    "Siem Reap": {
        "country": "Cambodia",
        "iata": "REP",
        "icao": "VDSR",
        "city": "Siem Reap",
        "runway": "05",
        "allRunway": "05/23"
    },
    "Phnom Penh": {
        "country": "Cambodia",
        "iata": "PNH",
        "icao": "VDPP",
        "city": "Phnom Penh",
        "runway": "23",
        "allRunway": "05/23"
    },
    "Auckland": {
        "country": "New Zealand",
        "iata": "AKL",
        "icao": "NZAA",
        "city": "Auckland",
        "runway": "23",
        "allRunway": "05L/23R, 05R/23L"
    },
    "Christchurch": {
        "country": "New Zealand",
        "iata": "CHC",
        "icao": "NZCH",
        "city": "Christchurch",
        "runway": "20",
        "allRunway": "02/20"
    },
    "Saipan": {
        "country": "Northern Mariana Islands",
        "iata": "SPN",
        "icao": "PGSN",
        "city": "Saipan",
        "runway": "07",
        "allRunway": "07/25"
    },
    "Guam": {
        "country": "Guam",
        "iata": "GUM",
        "icao": "PGUM",
        "city": "Guam",
        "runway": "06",
        "allRunway": "06L/24R, 06R/24L"
    },
    "Honolulu": {
        "country": "United States",
        "iata": "HNL",
        "icao": "PHNL",
        "city": "Honolulu",
        "runway": "08",
        "allRunway": "08L/26R, 08R/26L, 04L/22R, 04R/22L"
    },
    "Kona": {
        "country": "United States",
        "iata": "KOA",
        "icao": "PHKO",
        "city": "Kona",
        "runway": "17",
        "allRunway": "17/35"
    },
    "Las Vegas": {
        "country": "United States",
        "iata": "LAS",
        "icao": "KLAS",
        "city": "Las Vegas",
        "runway": "26",
        "allRunway": "01L/19R, 01R/19L, 08L/26R, 08R/26L"
    },
    "Los Angeles": {
        "country": "United States",
        "iata": "LAX",
        "icao": "KLAX",
        "city": "Los Angeles",
        "runway": "25",
        "allRunway": "06L/24R, 06R/24L, 07L/25R, 07R/25L"
    },
    "San Francisco": {
        "country": "United States",
        "iata": "SFO",
        "icao": "KSFO",
        "city": "San Francisco",
        "runway": "28",
        "allRunway": "10L/28R, 10R/28L, 01L/19R, 01R/19L"
    },
    "Seattle": {
        "country": "United States",
        "iata": "SEA",
        "icao": "KSEA",
        "city": "Seattle",
        "runway": "16",
        "allRunway": "16L/34R, 16C/34C, 16R/34L"
    },
    "Vancouver": {
        "country": "Canada",
        "iata": "YVR",
        "icao": "CYVR",
        "city": "Vancouver",
        "runway": "08",
        "allRunway": "08L/26R, 08R/26L, 12/30"
    },
};
